% General System Parameters ===============================================
StreamVelocityFunction = @UniformVelocity;
startEquil = true;
seafloorConstraint = false;
MWL = 60;
rho_f = 1020; % [kg/m^3]
tf = 30;  % s
tStep = 0.02;  % s
domain = [-20 140 -20 80 0 40];
perspective = [105 10]; % [Azimuth, Elevation]
DynamicModel = false;
SlacklineConstraint = false;
CFD = true;

% CFD options
options.test = 'what up?';
% =========================================================================

% Corner Buoys
BuoyNames = {'CornerBuoy1','CornerBuoy2','CornerBuoy3','CornerBuoy4'};
BuoyPositions = [[0;0;30],[0;60;30],[120;0;30],[120;60;30]];
for i = 1:size(BuoyNames,2);
    newBody('Name',BuoyNames{i},...
        'Mass',50,...
        'MMoInertia',[4;4;4],...
        'Vol',5,...
        'InitPosition',BuoyPositions(:,i),...
        'Drag',[1.2;1.2;1.2],...
        'TransDissipation',5,...
        'AngularDissipation',50,...
        'Dimensions',[6;6;6],...
        'BodyConstraints',[0;0;0;1;1;1]);
end

% Buoy Nodes
BuoyNodeNames = {'BuoyNode1','BuoyNode2','BuoyNode3','BuoyNode4'};
for i = 1:size(BuoyNodeNames,2)
    newNode('Name',BuoyNodeNames{i},...
        'Type','BodyFixed',...
        'ParentBody',BuoyNames{i},...
        'InitPosition',[0;0;0]);
end

% Anchor Nodes
AnchorNodeNames = {'AnchorNode1','AnchorNode2','AnchorNode3','AnchorNode4'};
AnchorNodePositions = [[-15;-15;0],[-15;75;0],[135;-15;0],[135;75;0]];
for i = 1:size(AnchorNodeNames,2)
    newNode('Name',AnchorNodeNames{i},...
        'Type','Fixed',...
        'InitPosition',AnchorNodePositions(:,i));
end

% Corner and side perimeter lines
CornerLineNames = {'CornerLine1','CornerLine2','CornerLine3','CornerLine4',...
    'Perimeter1','Perimeter2'};
CornerLineStartNodes = {AnchorNodeNames{1,:},BuoyNodeNames{1},BuoyNodeNames{2}};
CornerLineEndNodes = {BuoyNodeNames{1,:},BuoyNodeNames{3},BuoyNodeNames{4}};
CornerLineSegments = [6,6,6,6,12,12];
CornerLineLength = [36,36,36,36,90,90];
for i = 1:size(CornerLineNames,2)
    newLine('Name',CornerLineNames{i},...
        'StartNode',CornerLineStartNodes{i},...
        'EndNode',CornerLineEndNodes{i},...
        'LinearMass',4,...
        'Diameter',0.06,...
        'Length',CornerLineLength(i),...
        'UnitK',48000,...
        'TangentialDrag',0.6,...
        'NormalDrag',0.6,...
        'NumSegments',CornerLineSegments(i),...
        'DampingCoeff',2000);
end

% Turbines
TurbineNames = {'Turbine1','Turbine2'};
TurbinePositions = [[0;30;30],[120;30;30]];
TurbineNode1Names = {'Turbine1Node1','Turbine2Node1'};
TurbineNode2Names = {'Turbine1Node2','Turbine2Node2'};
for i = 1:size(TurbineNames,2)
    newBody('Name',TurbineNames{i},...
        'Mass',19300,...
        'MMoInertia',[4;4;4],...
        'Vol',1.6*9.67,...
        'InitPosition',TurbinePositions(:,i),...
        'Drag',[0.2;0.2;0.2],...
        'TransDissipation',5,...
        'AngularDissipation',50,...
        'Dimensions',[10;25;25]);
    
    newNode('Name',TurbineNode1Names{i},...
        'Type','BodyFixed',...
        'ParentBody',TurbineNames{i},...
        'InitPosition',[0;-3;1]);
    newNode('Name',TurbineNode2Names{i},...
        'Type','BodyFixed',...
        'ParentBody',TurbineNames{i},...
        'InitPosition',[0;3;1]);
end
    
% Turbine Lines
TurbineLineNames = {'TurbineLine1','TurbineLine2','TurbineLine3','TurbineLine4'};
TurbineStartNodes = {'BuoyNode1','Turbine1Node2','BuoyNode3','Turbine2Node2'};
TurbineEndNodes = {'Turbine1Node1','BuoyNode2','Turbine2Node1','BuoyNode4'};
for i = 1:size(TurbineLineNames,2)
    newLine('Name',TurbineLineNames{i},...
        'StartNode',TurbineStartNodes{i},...
        'EndNode',TurbineEndNodes{i},...
        'LinearMass',4,...
        'Diameter',0.06,...
        'UnitK',48000,...
        'TangentialDrag',0.6,...
        'Length',20,...
        'NormalDrag',0.6,...
        'NumSegments',4,...
        'DampingCoeff',2000);
end