% General System Parameters ===============================================
tFinal = 10;  % s
tStep = 0.005;  % s
StreamVelocity = @ZeroVelocity;
% =========================================================================

newBody('Name','Sphere',...
    'Mass',1611,...
    'MMoInertia',[(2/5)*1611*0.75^2;(2/5)*1611*0.75^2;(2/5)*1611*0.75^2],...
    'Vol',1.7671,...%(4/3)*pi*0.75^3,...
    'InitPosition',[0;0;16],...
    'Drag',[0.2;0.2;0.2],...
    'TransDissipation',0,...
    'AngularDissipation',0,...
    'Area',[pi*0.75^2;pi*0.75^2;pi*0.75^2],...
    'AppliedForcesGlobal',@SinusoidalForce,...
    'BodyConstraints',[0;0;0;1;1;1]);
    
newNode('Name','Line1EndNode',...
    'Type','BodyFixed',...
    'ParentBody','Sphere',...
    'InitPosition',[.001;0;0]);
newNode('Name','Line2EndNode',...
    'Type','BodyFixed',...
    'ParentBody','Sphere',...
    'InitPosition',[-.001*sin(pi/6);.001*cos(pi/6);0]);
newNode('Name','Line3EndNode',...
    'Type','BodyFixed',...
    'ParentBody','Sphere',...
    'InitPosition',[-.001*sin(pi/6);-.001*cos(pi/6);0]);

newNode('Name','Line1StartNode',...
    'Type','Fixed',...
    'InitPosition',[12;0;0]);
newNode('Name','Line2StartNode',...
    'Type','Fixed',...
    'InitPosition',[-12*sin(pi/6);12*cos(pi/6);0]);
newNode('Name','Line3StartNode',...
    'Type','Fixed',...
    'InitPosition',[-12*sin(pi/6);-12*cos(pi/6);0]);

LinearMass = pi*(0.01^2/4)*(1140);
Length = 20;
Diameter = 0.01;
UnitK = pi*(0.01^2/4)*6.369e8;
TangentialDrag = 0.1;
NormalDrag = 0.1;
NumSegments = 8;
DampingCoeff = 1;

newLine('Name','Line1',...
    'StartNode','Line1StartNode',...
    'EndNode','Line1EndNode',...
    'LinearMass',LinearMass,...
    'Length',Length,...
    'Diameter',Diameter,...
    'UnitK',UnitK,...
    'TangentialDrag',TangentialDrag,...
    'NormalDrag',NormalDrag,...
    'NumSegments',NumSegments,...
    'DampingCoeff',DampingCoeff);
newLine('Name','Line2',...
    'StartNode','Line2StartNode',...
    'EndNode','Line2EndNode',...
    'LinearMass',LinearMass,...
    'Length',Length,...
    'Diameter',Diameter,...
    'UnitK',UnitK,...
    'TangentialDrag',TangentialDrag,...
    'NormalDrag',NormalDrag,...
    'NumSegments',NumSegments,...
    'DampingCoeff',DampingCoeff);
newLine('Name','Line3',...
    'StartNode','Line3StartNode',...
    'EndNode','Line3EndNode',...
    'LinearMass',LinearMass,...
    'Length',Length,...
    'Diameter',Diameter,...
    'UnitK',UnitK,...
    'TangentialDrag',TangentialDrag,...
    'NormalDrag',NormalDrag,...
    'NumSegments',NumSegments,...
    'DampingCoeff',DampingCoeff);

